/*! \file ResDef.h
 *  \brief PrintConditionGUI用リソースID定義ファイル
 *  \author Sugita
 *  \date 2013/04/25 Sugita new
*/

#ifndef __RES_DEF_H__
#define __RES_DEF_H__

#include "CommonDef_OP.h"

// ==========================================================================
// Global definitions


#define ID_MESSAGE_ERROR		ERR_PRINT_CONDITION_SABER			//!< エラーコード = ID_MESSAGE_ERROR + リソースID


#define RESOURCE_STR_FILE	_T("strings_PrintConditionGUI.ini")
#define RESOURCE_STR	_T("STRING")	//! 読む込むリソースのセクション名
//! [STRING]セクションリソースID列挙
//! IDの並びはINIファイルの該当セクションと完全に一致している必要がある。
/* string identifiers */
enum
{
	IDS_PAGE_NAME = 1,//<! リソースIDは必ず「1」からはじめる。
	IDS_OPERATOR_ADD,
	IDS_OPERATOR_DELETE,
	IDS_BUTTON_CURRENT,
	IDS_BUTTON_EXIT,
	IDS_PRINT_SPEED_UNIT,
	IDS_BUTTON_LOCK,
	IDS_LENGTH,
	IDS_UNIT_MM,
	IDS_TONE,
	IDS_SAVE,
	IDS_HOLE,
	IDS_PERFORATED,
	IDS_SHEETS,
	IDS_PREPRINTED_MARK,
	IDS_PREPRINTED,
	IDS_EXIT,
	IDS_LABEL_PRINT_SETTING_NAME,
	IDS_LABLE_PRINT_SETTING_NAME_DUPLICATE,

	IDS_ROLLER,
	IDS_FAN,
	IDS_PRECOAT,

	IDS_NEW_ICC_PRESET,
	IDS_PRINT_SETTINGS_EDITED,

	IDS_DNS,

	IDS_DUPLICATING,
	IDS_DELETING,

	IDS_BASIC_SETUP,			// 基本設定 / Basic setup

	IDS_JI_DUPLICATING,

	IDS_UNIT_KW,
	IDS_N_IR,

	IDS_IMAGE_STORAGE,

	IDS_SUB_HEAT_ROLLER,

	IDS_VARIABLE_MAGNIFICATION,
	IDS_RIP_VARIABLE_MAGNIFICATION_SET,
	IDS_FRONT,
	IDS_BACK,
	
	IDS_PRIMER,

	/* リソースID数 */
	IDS_MAX
};

//! リソースINIファイル名
#define RESOURCE_MSG_STR_FILE	_T("strings_PrintConditionGUI.ini")
#define RESOURCE_MSG_STR	_T("MSG")			//!< 読む込むリソースのセクション名
//! [MSG]セクションリソースID列挙
//! IDの並びはINIファイルの該当セクションと完全に一致している必要がある。
enum
{
	IDM_DISCARD_CHANGES_CONFIRMATION = 1,//<! リソースIDは必ず「1」からはじめる。
	IDM_SET_CURRENT_PRINT_INFO,
	IDM_DELETE_CONFIRMATION,
	IDM_NOT_SELECT_PRINT_SETTING,
	IDM_OTHER_ITEMS,

	IDM_CHANGE_PAPER_TYPE_JOB_LIST_SCREEN,
	IDM_CHANGE_PRECOAT_JOB_LIST_SCREEN,
	IDM_NOT_USE_ICCPRESET,
	IDM_COMMIT_CLICK_JOB_LIST_SCREEN,
	IDM_COMMIT_CLICK_SYSTEM_SETTING_SCREEN,
	IDM_ICC_PROFILE_IS_ASSIGNED_OR_NOT,

	IDM_DUPLICATE_NAME_EXISTS,
	IDM_NOT_DELETE_PAPER_TYPE,
	IDM_FAILED_COPYING_JI_PARAMETER,
	IDM_FAILED_UPDATE_THE_MANAGEMENT_FILE,
	IDM_NOT_DELETE_HEAD_ALIGNMENT,

	IDM_ERR_DRYER_SETT_IS_USED_IN_OTHERS,

	IDM_SELECT_DIFFERENT_NAME,

	IDM_MSG_DELETE_NOW,

	IDM_MSG_ERROR_PRECOAT_AND_SPEED,

	IDM_MSG_BLANK_NOT_ALLOWED,
	IDM_MSG_PAPER_SIZE_IS_CHANGED,

	IDM_CHANGE_NOTSAVED_PREVIEW_NOT_CORRECT_SIZE,	// 未保存の項目があります。\nプレビュー表示の画像サイズが正しくならない可能性がありますが、このまま処理を続行しますか？
	IDM_MSG_NOT_DELETE_PRINT_CONDITION,

	IDM_ERR_PROHIBITCHARS_PRINTCONDITION_NAME,
	IDM_ERR_PROHIBITCHARS_PAPERTYPE_NAME,
	// IDM_ERR_PROHIBITCHARS_LEVELTUNE_NAME,	// 禁止文字チェックは不要になった
	// IDM_ERR_PROHIBITCHARS_ICCPRESET_NAME,	// 禁止文字チェックは不要になった

	IDM_MSG_PRINTSPEED_BASE,
	IDM_MSG_PRINTSPEED_UNDERCOAT,
	IDM_MSG_PRINTSPEED_PROTECTORCOAT,

	IDM_ERR_PRINTSPEED_BASE,
	IDM_ERR_PRINTSPEED_TENSION,
	IDM_ERR_PRINTSPEED_UNDERCOAT,
	IDM_ERR_PRINTSPEED_PROTECTORCOAT,
	IDM_ERR_NO_TONECURVE_FILE,

	IDM_ERR_CANNOT_DELETE_PRINT_SETTING,

	IDM_MSG_PAPER_SIZE_IS_CHANGED_IPDS,

	IDM_ERR_IRDRYER_BASE,
	IDM_ERR_IRDRYER_PRINTSPEED,
	IDM_ERR_IRDRYER_PAPERTHICKNESS,

	IDM_DELETE_BASE_CODITION,
	IDM_ERR_CANNOT_SET_MONOTONE,

	/* リソースID数 */
	IDM_MAX
};

//! リソースINIファイル名
#define RESOURCE_BMP_FILE	_T("guis_PrintConditionGUI.ini")	

//! 読む込むリソースのセクション名(画像用)
#define RESOURCE_BMP	_T("BITMAP")
//! [BITMAP]セクションリソースID列挙
//! IDの並びはINIファイルの該当セクションと完全に一致している必要がある。
enum
{
	IDB_EXIT = 1,//<! リソースIDは必ず「1」からはじめる。

	IDB_PRINT_SETTING,
	IDB_LOCK,
	IDB_ROLLTYPE_NONE,
	IDB_ROLLTYPE_HOLE,
	IDB_ROLLTYPE_HOLE_PERF,
	IDB_ROLLTYPE_PREPRINTMARK_F,
	IDB_ROLLTYPE_PREPRINT,
	IDB_ROLLTYPE_PREPRINTMARK_B,

	IDB_SET_CURRENT_ROLL,
	IDB_PRINT_MODE,
	IDB_PRINT_SPEED_ICON,
	IDB_TENSION_ICON,
	IDB_PRINT_HEAD_ALIGNMENT,
	IDB_PAPER_TYPE_ICON,
	IDB_PRECOAT_ICON,
	IDB_PRINTER_2_ICON,
	IDB_PRINTER_1_ICON,
	IDB_OVERCOAT_ICON,
	IDB_DRYER_SETTINGS_ICON,
	IDB_PAGE_WIDTH_ICON,
	IDB_PAGE_FEED_ICON,
	IDB_PAPER_THICKNESS_ICON,
	IDB_SAVE,
	IDB_PAPER_PUNCH,
	IDB_TRACKHOLES_PERFORATION,
	IDB_PAPER_MARK_FRONT,
	IDB_PAPER_PREPRINTED,
	IDB_DELETE,
	IDB_ICON_DEG,
	IDB_PRECOAT_IMAGE,
	IDB_DRYER_IMAGE_FAN_OFF,
	IDB_DRYER_IMAGE_FAN_ON,
	IDB_PAPER_MARK_BACK,
	IDB_GRAY_BACKGROUND,
	IDB_ROLLTYPE_MACHINE_CUTTER,
	IDB_ICCPRESET,
	IDB_UNLOCK_ICON,
	IDB_JET_INSPECTION,
	IDB_DNS_ICON,
	IDB_BASIC_SETUP,
	IDB_VERIFY_MARK,

	IDB_OUTPUTCOLOR_CMYK,
	IDB_OUTPUTCOLOR_CMYKRO,
	IDB_IMAGE_STOAGE,

	IDB_SUB_HEAT_ROLLER,

	IDB_CORRECT_PRINT_POS,
	IDB_ICON_SIDE_FRONT,
	IDB_ICON_SIDE_BACK,
	IDB_ICON_SIDE_FRONT_MINI,
	IDB_ICON_SIDE_BACK_MINI,
	IDB_LEFT_RIGHT_MINI,
	IDB_UP_DOWN_MINI,
	IDB_LEFT_RIGHT,
	IDB_UP_DOWN,
	
	IDB_PRIMER,

	IDB_WEIGHT_GSM_ICON,

	/* リソースID数 */
	IDB_MAX

};

#endif // __RES_DEF_H__
