/**
 * @file	ResDef.h
 * @brief	PrintConditionExporter用リソースID定義ファイル
 * @author pt.ju-tanaka
 * @date 2019/2/5 pt.ju-tanaka new
 * @date 2022/04/27 cec.k-miyachi #9545: 印刷条件のインポート／エクスポート（自動ダイバート設定）
**/

#pragma once

#include "CommonDef_OP.h"

// ==========================================================================
// Global definitions


#define ID_MESSAGE_ERROR		ERR_PRINT_CONDITION_EXPORTER			//!< エラーコード = ID_MESSAGE_ERROR + リソースID

#define RESOURCE_STR_FILE	_T("strings_PrintConditionExporter.ini")	//! リソースINIファイル名 strings_PrintConditionExporter.ini
#define RESOURCE_STR	_T("STRING")	//! 読む込むリソースのセクション名
//! [STRING]セクションリソースID列挙
//! IDの並びはINIファイルの該当セクションと完全に一致している必要がある。
/* string identifiers */
enum
{
	IDS_PARAM_PAPER_TYPE = 1,
	IDS_PARAM_PAPERTHICKNESS,
	IDS_PARAM_PAGEWIDTH,
	IDS_PARAM_PAPER_FEED,
	IDS_PARAM_PAPER_FEED_UNIT,
	IDS_PARAM_TENSION,
	IDS_PARAM_PAPER_OP_PUNCH,
	IDS_PARAM_PAPER_OP_PERFORATION,
	IDS_PARAM_MARK,
	IDS_PARAM_MARK_OFFSET,
	IDS_PARAM_PRE_PRINT,
	IDS_PARAM_DRYER_TEMP_F,
	IDS_PARAM_DRYER_TEMP_B,
	IDS_PARAM_TONE_CURVE_F,
	IDS_PARAM_TONE_CURVE_B,
	IDS_PARAM_INFORMATION_SHEET,
	IDS_PARAM_FLUSHING_PATTERN_CMYK,
	IDS_PARAM_FLUSHING_PATTERN_OFFSET,
	IDS_PARAM_FLUSHING_PATTERN_POS_Y,
	IDS_PARAM_FLUSHING_PATTERN_POS_Y_BACK,
	IDS_PARAM_FLUSHING_PAGE,
	IDS_PARAM_FLUSHING_PAGE_INTERVAL,
	IDS_PARAM_BEFOREJOB,
	IDS_PARAM_COUNT_BEFOREJOB,
	IDS_PARAM_AFTERJOB,
	IDS_PARAM_OFFSET_F,
	IDS_PARAM_OFFSET_B,
	IDS_PARAM_IMAGE_LAYOUT_FRONT_X,
	IDS_PARAM_IMAGE_LAYOUT_FRONT_Y,
	IDS_PARAM_IMAGE_LAYOUT_BACK_X,
	IDS_PARAM_IMAGE_LAYOUT_BACK_Y,
	IDS_PARAM_SIDE_CHECK_MARK,
	IDS_PARAM_SIDE_CHECK_MARK_KIND,
	IDS_PARAM_ERR_CONS_SHEET,
	IDS_PARAM_SIDE_CHECK_MARK_OFFSET_FRONT_X,
	IDS_PARAM_SIDE_CHECK_MARK_OFFSET_BACK_X,
	IDS_PARAM_SIDE_CHECK_MARK_OFFSET_BACK_Y,
	IDS_PARAM_POST_MARK_KIND,
	IDS_PARAM_POST_MARK_SIZE_X,
	IDS_PARAM_POST_MARK_SIZE_Y,
	IDS_PARAM_POST_MARK_OFFSET_F,
	IDS_PARAM_POST_MARK_OFFSET_B,
	IDS_PARAM_POST_READY_SHEETS,
	IDS_DATA_UNIT_MM,
	IDS_DATA_UNIT_INCH,
	IDS_DATA_UNIT_1P2INCH,
	IDS_DATA_UNIT_1P6INCH,
	IDS_DATA_TRUE,
	IDS_DATA_FALSE,
	IDS_DATA_POST_MARK_NONE,
	IDS_DATA_POST_MARK_FRONT,
	IDS_DATA_POST_MARK_BACK,
	IDS_DATA_POST_MARK_BOTH,
	IDS_DATA_FLUSHING_PATTERN_LINE1,
	IDS_DATA_FLUSHING_PATTERN_LINE2,
	IDS_DATA_FLUSHING_PATTERN_LINE3,
	IDS_DATA_FLUSHING_PATTERN_LINE4,
	IDS_DATA_FLUSHING_PATTERN_LINE5,
	IDS_DATA_FLUSHING_PATTERN_LINE6,
	IDS_DATA_FLUSHING_PATTERN_LINE7,
	IDS_DATA_FLUSHING_PATTERN_LINE8,
	IDS_DATA_FLUSHING_PATTERN_LINE9,
	IDS_DATA_FLUSHING_PATTERN_LINE10,
	IDS_DATA_FLUSHING_PATTERN_LINE11,
	IDS_DATA_FLUSHING_PATTERN_LINE12,
	IDS_DATA_FLUSHING_PATTERN_LINE13,
	IDS_DATA_FLUSHING_PATTERN_LINE14,
	IDS_DATA_FLUSHING_PATTERN_LINE15,
	IDS_DATA_FLUSHING_PATTERN_LINE16,
	IDS_DATA_FLUSHING_PATTERN_LINE32,
	IDS_DATA_FLUSHING_PATTERN_STAR1,
	IDS_DATA_FLUSHING_PATTERN_STAR2,
	IDS_DATA_FLUSHING_PATTERN_STAR3,
	IDS_DATA_FLUSHING_PATTERN_STAR4,
	IDS_DATA_FLUSHING_PATTERN_STAR8,
	IDS_DATA_FLUSHING_PATTERN_LINE1_STAR,
	IDS_DATA_FLUSHING_PATTERN_LINE2_STAR,
	IDS_DATA_FLUSHING_PATTERN_LINE4_STAR,
	IDS_DATA_FLUSHING_PATTERN_LINE8_STAR,
	IDS_DATA_FLUSHING_PATTERN_LINE16_STAR,
	IDS_DATA_FLUSHING_PATTERN_LINE32_STAR,
	IDS_DATA_LINE_FLUSHING_OUTPUT_TO_MULTIPLE,
	IDS_DATA_LINE_FLUSHING_FRONT_INSERTION_INTERVAL,
	IDS_DATA_LINE_FLUSHING_FRONT_OFFSET,
	IDS_DATA_LINE_FLUSHING_BACK_INSERTION_INTERVAL,
	IDS_DATA_LINE_FLUSHING_BACK_OFFSET,
	IDS_DATA_LINE_FLUSHING_LINE_TYPE,
	IDS_DATA_CROSS_STICH,
	IDS_DATA_CHECK_MARK_NONE,
	IDS_DATA_CHECK_MARK_PRINT,
	IDS_DATA_CHECK_MARK_PRINT_BARCODE,
	IDS_EXIT_PROGRESS,
	IDS_PARAM_FLUSHING_PATTERN_MICR,
	IDS_PARAM_PRINT_TIMING,
	IDS_PARAM_PRINT_MODE,
	IDS_PARAM_PRINT_SPEED,
	IDS_PARAM_MICR_PRINT,
	IDS_PARAM_PAPER_SAVE_MODE,
	IDS_PARAM_DNS,
	IDS_PARAM_HEAT_FAN_TEMP_F,
	IDS_PARAM_HEAT_FAN_TEMP_B,
	IDS_PARAM_IR_POWER_F,
	IDS_PARAM_IR_POWER_B,
	IDS_PARAM_FLUSHING_LINE_POS_BOTTOM,
	IDS_PARAM_FLUSHING_LINE_OPTIONS,
	IDS_PARAM_INSPECTION_PARAMATER,
	IDS_PARAM_TEMP_MASK_FILEPATH,
	IDS_PARAM_NONINSPECT_AREA_LEFT_F,
	IDS_PARAM_NONINSPECT_AREA_RIGHT_F,
	IDS_PARAM_NONINSPECT_AREA_LEFT_B,
	IDS_PARAM_NONINSPECT_AREA_RIGHT_B,
	IDS_PARAM_NONINSPECT_RECT_F,
	IDS_PARAM_NONINSPECT_RECT_B,
	IDS_PARAM_DECODE,
	IDS_PARAM_DECODE_ERR_CONS_SHEET,
	IDS_PARAM_DECODE_LABEL_NAME_F,
	IDS_PARAM_DECODE_TYPE_F,
	IDS_PARAM_DECODE_POS_F,
	IDS_PARAM_DECODE_SIZE_F,
	IDS_PARAM_DECODE_ANGLE_F,
	IDS_PARAM_DECODE_ERROR_PROC_F,
	IDS_PARAM_DECODE_LABEL_NAME_B,
	IDS_PARAM_DECODE_TYPE_B,
	IDS_PARAM_DECODE_POS_B,
	IDS_PARAM_DECODE_SIZE_B,
	IDS_PARAM_DECODE_ANGLE_B,
	IDS_PARAM_DECODE_ERROR_PROC_B,
	IDS_DATA_FLUSHING_OPTION_C0_STANDARD,
	IDS_DATA_FLUSHING_OPTION_C0_CROSS_STITCH,
	IDS_DATA_FLUSHING_OPTION_NONE_STANDARD,
	IDS_DATA_FLUSHING_OPTION_NONE_CROSS_STITCH,
	IDS_DATA_FLUSHING_OPTION_S0_STANDARD,
	IDS_DATA_FLUSHING_OPTION_S0_CROSS_STITCH,
	IDS_DATA_FLUSHING_OPTION_S2_STANDARD,
	IDS_DATA_FLUSHING_OPTION_S2_CROSS_STITCH,
	IDS_DATA_TOP,
	IDS_DATA_BOTTOM,
	IDS_PARAM_SUB_DRYER_TEMP_F,
	IDS_PARAM_SUB_DRYER_TEMP_B,
	IDS_PARAM_FLUSHING_PAGE_NAME_NONE,
	IDS_PARAM_RIP_AUTO_MANIFICATION,
	IDS_PARAM_RIFERENCE_FACE,
	IDS_PARAM_MANIFICATION_FRONT_X,
	IDS_PARAM_MANIFICATION_FRONT_Y,
	IDS_PARAM_MANIFICATION_BACK_X,
	IDS_PARAM_MANIFICATION_BACK_Y,
	IDS_DATA_STOP_PRINTING,
	IDS_DATA_KEEP_PRINTING,
	IDS_PARAM_CLEANING_JUDGMENT_LEVEL_BEFORE_JOB,
	IDS_PARAM_CLEANING_JUDGMENT_LEVEL_AFTER_JOB,
	IDS_PARAM_PRINT_STOP_SETTING,
	// ADD --> #9545: 印刷条件のインポート／エクスポート（自動ダイバート設定）
	IDS_PARAM_ADJUST_SHEETSIZE,
	IDS_PARAM_ADJUST_SHEETLENGTH,
	IDS_PARAM_ADJUST_AFTERJOBSHEET,
	IDS_PARAM_ADJUST_AFTERJOBSHEET_SET,
	IDS_PARAM_ADJUST_AFTERJOBSHEET_STOP,
	IDS_PARAM_ADJUST_AFTERJOBSHEET_NOSET,
	IDS_PARAM_ADJUST_AFTERJOBSHEET_COUNT,
	// ADD <-- #9545: 印刷条件のインポート／エクスポート（自動ダイバート設定）
	/* リソースID数 */
	IDS_MAX
};

//! リソースINIファイル名
#define RESOURCE_MSG_STR_FILE	_T("strings_PrintConditionExporter.ini")
#define RESOURCE_MSG_STR	_T("MSG")			//!< 読む込むリソースのセクション名
//! [MSG]セクションリソースID列挙
//! IDの並びはINIファイルの該当セクションと完全に一致している必要がある。
enum
{
	IDM_ERR_NETWORK = 1,
	IDM_ERR_CRATE_OUTPUT_FOLDER,
	IDM_ERR_NETWORK_XML,
	IDM_ERR_CRATE_OUTPUT_FOLDER_XML,

	/* リソースID数 */
	IDM_MAX
};


